import type { Metadata } from "next";
import { Chivo_Mono } from "next/font/google"; // Updated import
import "./globals.css";

const chivoMono = Chivo_Mono({ subsets: ["latin"], weight: "400" }); // Updated font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chivoMono.className} custom-vcr-font`}>
        {children}
      </body>
    </html>
  );
}
